In [2]:
import requests
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support import ui

# Define header to prevent errors
user_agent = "Mozilla/44.0.2 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/9.0.2"
headers = {'User-Agent': user_agent}

In [3]:
# Set webdriver - global
d = webdriver.Chrome("C:\\Users\\Shrivatav\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [4]:
wait = ui.WebDriverWait(d, 10)

In [5]:
def get_tags_from_url(input_url):
    # Get response from url
    response = requests.get(input_url, headers = headers)
    # Encode response for parsing
    html = response.text.encode('utf-8')
    # Soupify the response
    soup = BeautifulSoup(html, "lxml")
    # Get tags - they are contained in class "taLnk" as hyperlinked elements
    tag_elements = soup.findAll("a", {"class":"taLnk"})
    
    dict_of_tags = {}
    
    if (len(tag_elements) != 0):
        # Iterate over tag_elements and exctract those which have parentheses 
        # as they are the relevant items
        print("Yes")
        tags_list = []
        for i in tag_elements:
            strng = i.string
            if("(" in strng):
                tags_list.append(strng)
    
        # Create final list of tags
        for item in tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value
    else:
        # Second kind of web page with list of 'Things to Do' at the bottom of the page
        # Use selenium to automate browser functionality
        # Browser opens the input_url, scrolls till the bottom of the page,
        # clicks on 'Show All' button, the entire list becomes visible; then scrapes it
        print("Nope")
        #time.sleep(5)
        '''
        d.get(input_url)
        WebDriverWait(d, 20).until(EC.presence_of_element_located((By.XPATH, '//*[@id="component_3"]/div/div/div[12]/div[1]/div/div/div/div[1]/span')))
        d.execute_script("arguments[0].scrollIntoView();", 
                 d.find_element_by_xpath('//*[@id="component_3"]/div/div/div[12]/div[1]/div/div/div/div[1]/span'))
        d.execute_script("arguments[0].click();", 
                 d.find_element_by_xpath('//*[@id="component_3"]/div/div/div[12]/div[1]/div/div/div/div[1]/span'))
        html = d.page_source
        soup = BeautifulSoup(html, 'lxml')

        items = soup.findAll('a', {'class':'attractions-attraction-overview-main-Pill__pill--23S2Q'})
        '''
        time.sleep(5)
        d.get(input_url)
        show_more = wait.until(lambda d: d.find_element_by_css_selector("[class='ui_container'] div:nth-of-type(1) .caret-down"))
        d.execute_script("arguments[0].click();",show_more)
        soup = BeautifulSoup(d.page_source,"lxml")
        items = [item.text for item in soup.select("[class='ui_container'] div:nth-of-type(1) a[href^='/Attractions-']")]
        
        #tags_list = []
        #for item in items:
        #    tags_list.append(item.get_text())
        # Create final list of tags
        for item in items:#tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value
        
    return dict_of_tags

In [6]:
mini_url_dict = {
    "New_York_City" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60763-Activities-New_York_City_New_York.html"
    },
    "San_Francisco" : {
        "type" : "City",
        "url": "https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html"
    },
    "Los_Angeles" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g32655-Activities-Los_Angeles_California.html"
    },
    "Las_Vegas" : {
        "type" : "City",
         "url" : "https://www.tripadvisor.com/Attractions-g45963-Activities-Las_Vegas_Nevada.html"   
    },
    "Grand_Canyon_National_Park" : {
        "type" : "Natural",
        "url": "https://www.tripadvisor.com/Attractions-g143028-Activities-Grand_Canyon_National_Park_Arizona.html"
    },
    "Yellowstone_National_Park" : {
        "type" : "Natural",
        "url": "https://www.tripadvisor.com/Attractions-g60999-Activities-Yellowstone_National_Park_Wyoming.html"
    },
    "Disneyland_Anaheim" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g29092-Activities-Anaheim_California.html"
    },
    "Washington_DC" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g28970-Activities-Washington_DC_District_of_Columbia.html"
    },
    "Yosemite_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g61000-Activities-Yosemite_National_Park_California.html"
    },
    "Miami" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34438-Activities-Miami_Florida.html"
    },
    "Orlando" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34515-Activities-Orlando_Florida.html"
    },
    "Zion_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143057-Activities-Zion_National_Park_Utah.html"
    },
    "Santa_Monica" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33052-Activities-Santa_Monica_California.html"
    },
    "Seattle" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60878-Activities-Seattle_Washington.html"
    },
    "Boston" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60745-Activities-Boston_Massachusetts.html"
    },
    "San_Diego" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60750-Activities-San_Diego_California.html"
    },
    "Florida_Keys" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34340-Activities-Florida_Keys_Florida.html"
    },
    "Hawaii" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g28932-Activities-Hawaii.html"
    },
    "Bryce_Canyon_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143015-Activities-Bryce_Canyon_National_Park_Utah.html"
    },
    "Glacier_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143026-Activities-Glacier_National_Park_Montana.html"
    },
    "Grand_Teton_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143029-Activities-Grand_Teton_National_Park_Wyoming.html"
    },
    "New_Orleans" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60864-Activities-New_Orleans_Louisiana.html"
    },
    "Arches_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143011-Activities-Arches_National_Park_Utah.html"
    },
    "Monterey" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g32737-Activities-Monterey_Monterey_County_California.html"
    },
    "Niagara_Falls" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g48261-Activities-Niagara_Falls_New_York.html"
    },
    "Sequoia_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143050-Activities-Sequoia_and_Kings_Canyon_National_Park_California.html"
    },
    "Sedona" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g31352-Activities-Sedona_Arizona.html"
    },
    "Lake_Tahoe" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g155987-Activities-Lake_Tahoe_California_California.html"
    },
    "Philadelphia" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60795-Activities-Philadelphia_Pennsylvania.html"
    },
    "Joshua_Tree_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143037-Activities-Joshua_Tree_National_Park_California.html"
    },
    "Santa Barbara" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33045-Activities-Santa_Barbara_California.html"
    },
    #"Redwood_National_and_State_Parks" : "https://www.tripadvisor.com/Attractions-g2193168-Activities-Redwood_National_Park_California.html",
    "Denver" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33388-Activities-Denver_Colorado.html"
    },
    "Austin" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g30196-Activities-Austin_Texas.html"
    },
    "Denali_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143022-Activities-Denali_National_Park_and_Preserve_Alaska.html"
    },
    "Houston" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g56003-Activities-Houston_Texas.html"
    },
    "Portland" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g52024-Activities-Portland_Oregon.html"
    },
    "Death_Valley_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143021-Activities-Death_Valley_National_Park_California.html"
    },
    "Monument_Valley" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g57072-Activities-Monument_Valley_Utah.html"
    }
}

In [7]:
places_and_tags_dict = {}

In [8]:
'''
for k,v in mini_url_dict.items():
    print(k)
    dict_tags = get_tags_from_url(v)
    places_and_tags_dict[k] = dict_tags
'''

# Modified for loop for assigning values 
# Includes 'Type' of destination
for k,v in mini_url_dict.items():
    print(k)
    dict_tags = get_tags_from_url(v["url"])
    places_and_tags_dict[k] = {}
    places_and_tags_dict[k] = dict_tags
    places_and_tags_dict[k]["type"] = v["type"]
    #places_and_tags_dict[k]["url"] = dict_tags
    
d.quit()

New_York_City
Nope
San_Francisco
Nope
Los_Angeles
Nope
Las_Vegas
Nope
Grand_Canyon_National_Park
Nope
Yellowstone_National_Park
Nope
Disneyland_Anaheim
Nope
Washington_DC
Nope
Yosemite_National_Park
Nope
Miami
Nope
Orlando
Nope
Zion_National_Park
Yes
Santa_Monica
Nope
Seattle
Nope
Boston
Nope
San_Diego
Nope
Florida_Keys
Nope
Hawaii
Yes
Bryce_Canyon_National_Park
Yes
Glacier_National_Park
Yes
Grand_Teton_National_Park
Nope
New_Orleans
Nope
Arches_National_Park
Yes
Monterey
Yes
Niagara_Falls
Nope
Sequoia_National_Park
Yes
Sedona
Nope
Lake_Tahoe
Nope
Philadelphia
Nope
Joshua_Tree_National_Park
Yes
Santa Barbara
Nope
Denver
Nope
Austin
Nope
Denali_National_Park
Nope
Houston
Nope
Portland
Nope
Death_Valley_National_Park
Yes
Monument_Valley
Nope

In [ ]:
places_and_tags_dict

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame.from_dict(places_and_tags_dict, orient = 'index')

In [11]:
df

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Transportation,...,Food & Drink,Classes & Workshops,Boat Tours & Water Sports,Traveler Resources,Events,Day Trips,Water & Amusement Parks,Zoos & Aquariums,Casinos & Gambling,type
Arches_National_Park,NaN,NaN,NaN,NaN,7,NaN,NaN,13,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Natural
Austin,118,217,128,74,83,43,57,129,76,17,...,58,27,54,9,3,NaN,2,3,1,City
Boston,144,162,158,40,157,54,63,68,54,63,...,52,13,43,19,NaN,12,NaN,2,1,City
Bryce_Canyon_National_Park,1,NaN,1,NaN,10,NaN,NaN,18,NaN,1,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Natural
Death_Valley_National_Park,NaN,NaN,1,NaN,23,NaN,1,15,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Natural
Denali_National_Park,5,NaN,35,NaN,4,4,3,38,1,2,...,NaN,NaN,8,3,NaN,NaN,NaN,NaN,1,Natural
Denver,82,179,86,69,57,42,44,54,51,36,...,82,17,9,3,NaN,4,2,2,NaN,City
Disneyland_Anaheim,10,12,11,6,13,8,4,8,19,13,...,10,3,1,2,NaN,9,7,NaN,NaN,City
Florida_Keys,193,74,811,84,69,12,73,858,27,19,...,25,17,742,10,1,NaN,NaN,7,1,City
Glacier_National_Park,NaN,NaN,3,NaN,3,NaN,NaN,21,NaN,NaN,...,NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,Natural
Grand_Canyon_National_Park,4,NaN,19,NaN,40,1,4,50,NaN,NaN,...,NaN,1,2,1,NaN,8,NaN,NaN,NaN,Natural
Grand_Teton_National_Park,NaN,NaN,17,NaN,14,1,1,30,NaN,NaN,...,NaN,NaN,9,2,NaN,2,NaN,NaN,NaN,Natural
Hawaii,65,9,426,38,147,45,43,506,8,13,...,34,19,223,4,NaN,NaN,1,5,NaN,City
Houston,98,283,45,70,80,60,68,58,113,65,...,36,19,6,9,1,2,2,2,2,City
Joshua_Tree_National_Park,NaN,NaN,3,NaN,11,NaN,NaN,16,NaN,NaN,...,NaN,2,NaN,1,NaN,NaN,NaN,NaN,NaN,Natural
Lake_Tahoe,44,16,90,34,25,3,21,191,21,4,...,7,6,56,5,NaN,NaN,NaN,NaN,NaN,Natural
Las_Vegas,184,353,284,167,84,184,74,253,297,42,...,27,36,19,9,10,44,8,9,78,City
Los_Angeles,226,342,288,448,197,130,134,159,175,73,...,51,41,31,8,6,8,2,4,1,City
Miami,126,126,277,109,54,25,61,255,67,66,...,27,22,184,7,2,7,5,7,3,City
Monterey,30,4,42,16,17,7,18,45,12,6,...,15,NaN,23,5,1,NaN,NaN,1,NaN,City
Monument_Valley,4,NaN,22,NaN,1,NaN,1,16,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Natural
New_Orleans,265,249,251,44,118,52,121,98,29,33,...,56,21,40,8,7,1,2,2,2,City
New_York_City,918,889,727,722,474,438,309,216,187,143,...,117,99,74,30,14,13,2,1,1,City
Niagara_Falls,11,16,26,2,12,4,9,17,9,11,...,2,NaN,6,1,NaN,1,1,1,1,Natural
Orlando,119,153,113,83,38,49,25,131,101,150,...,34,22,46,7,NaN,20,34,5,NaN,City
Philadelphia,120,256,80,32,201,62,106,33,60,18,...,45,14,10,14,NaN,4,NaN,1,1,City
Portland,160,217,137,59,132,51,62,102,65,21,...,102,19,27,7,1,4,1,3,2,City
San_Diego,140,220,334,119,111,58,77,323,88,29,...,113,27,189,10,1,9,5,4,NaN,City
San_Francisco,330,339,339,96,409,95,111,168,69,57,...,133,34,50,19,4,30,NaN,4,NaN,City
Santa Barbara,40,28,89,35,50,13,25,67,5,13,...,72,9,28,6,NaN,NaN,NaN,2,NaN,City
Santa_Monica,39,32,41,78,18,11,27,38,11,5,...,2,11,13,5,NaN,NaN,1,1,NaN,City
Seattle,215,225,178,49,106,51,78,123,78,47,...,96,29,64,9,8,5,4,2,NaN,City
Sedona,137,7,91,87,26,3,35,114,12,2,...,13,17,5,5,NaN,9,NaN,NaN,NaN,Natural
Sequoia_National_Park,NaN,NaN,1,NaN,22,NaN,NaN,31,NaN,NaN,...,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,Natural
Washington_DC,81,185,166,93,211,45,107,58,36,42,...,31,14,21,12,20,7,1,1,NaN,City
Yellowstone_National_Park,2,NaN,15,1,27,1,NaN,49,NaN,1,...,NaN,NaN,3,8,NaN,2,NaN,NaN,NaN,Natural
Yosemite_National_Park,2,NaN,13,NaN,28,2,3,49,NaN,3,...,NaN,2,5,5,NaN,4,NaN,NaN,NaN,Natural
Zion_National_Park,NaN,NaN,2,NaN,9,NaN,NaN,33,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,Natural

In [12]:
df.fillna(0, inplace = True)
df.to_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data_new.csv")

Suggested Steps:
1. Remove columns that have more than x% of rows 0.
2. Separate destinations into multiple categories - Cities, National Parks and Beaches
3. Train models on these separated datasets
4. Add destinations - Death Valley, Monument Valley, Portland, Moab, Hawaii islands

Normalise the data:
Minmax standardization to bring all values in the range 1-10

Not all columns are useful. Keep only required columns

In [13]:
cols_to_keep = ["Shopping", "Nightlife", "Tours", "Spas & Wellness", "Sights & Landmarks", "Concerts & Shows", "Museums", 
                "Outdoor Activities", "Fun & Games", "Nature & Parks", "Food & Drink", "type"]

In [15]:
df_new = df[cols_to_keep]
df_new.columns

Index(['Shopping', 'Nightlife', 'Tours', 'Spas & Wellness',
       'Sights & Landmarks', 'Concerts & Shows', 'Museums',
       'Outdoor Activities', 'Fun & Games', 'Nature & Parks', 'Food & Drink',
       'type'],
      dtype='object')

Separate data into 'Natural' and 'City' categories. 'Natural' will have all National Parks, beaches and other places which are primarily known for their natural beauty, and 'Cities' will have all cities.

In [47]:
df_nature = df_new[df_new["type"] == "Natural"]
df_nature

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Nature & Parks,Food & Drink,type
Arches_National_Park,0,0,0,0,7,0,0,13,0,22,0,Natural
Bryce_Canyon_National_Park,1,0,1,0,10,0,0,18,0,20,0,Natural
Death_Valley_National_Park,0,0,1,0,23,0,1,15,0,34,0,Natural
Denali_National_Park,5,0,35,0,4,4,3,38,1,13,0,Natural
Glacier_National_Park,0,0,3,0,3,0,0,21,0,44,0,Natural
Grand_Canyon_National_Park,4,0,19,0,40,1,4,50,0,40,0,Natural
Grand_Teton_National_Park,0,0,17,0,14,1,1,30,0,28,0,Natural
Joshua_Tree_National_Park,0,0,3,0,11,0,0,16,0,23,0,Natural
Lake_Tahoe,44,16,90,34,25,3,21,191,21,82,7,Natural
Monument_Valley,4,0,22,0,1,0,1,16,0,3,0,Natural
Niagara_Falls,11,16,26,2,12,4,9,17,9,17,2,Natural
Sedona,137,7,91,87,26,3,35,114,12,61,13,Natural
Sequoia_National_Park,0,0,1,0,22,0,0,31,0,37,0,Natural
Yellowstone_National_Park,2,0,15,1,27,1,0,49,0,107,0,Natural
Yosemite_National_Park,2,0,13,0,28,2,3,49,0,82,0,Natural
Zion_National_Park,0,0,2,0,9,0,0,33,0,36,0,Natural

In [29]:
df_cities = df_new[df_new["type"] == "City"]
df_cities

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Nature & Parks,Food & Drink,type
Austin,118,217,128,74,83,43,57,129,76,65,58,City
Boston,144,162,158,40,157,54,63,68,54,53,52,City
Denver,82,179,86,69,57,42,44,54,51,33,82,City
Disneyland_Anaheim,10,12,11,6,13,8,4,8,19,3,10,City
Florida_Keys,193,74,811,84,69,12,73,858,27,94,25,City
Hawaii,65,9,426,38,147,45,43,506,8,203,34,City
Houston,98,283,45,70,80,60,68,58,113,49,36,City
Las_Vegas,184,353,284,167,84,184,74,253,297,61,27,City
Los_Angeles,226,342,288,448,197,130,134,159,175,92,51,City
Miami,126,126,277,109,54,25,61,255,67,54,27,City
Monterey,30,4,42,16,17,7,18,45,12,14,15,City
New_Orleans,265,249,251,44,118,52,121,98,29,26,56,City
New_York_City,918,889,727,722,474,438,309,216,187,121,117,City
Orlando,119,153,113,83,38,49,25,131,101,48,34,City
Philadelphia,120,256,80,32,201,62,106,33,60,41,45,City
Portland,160,217,137,59,132,51,62,102,65,132,102,City
San_Diego,140,220,334,119,111,58,77,323,88,88,113,City
San_Francisco,330,339,339,96,409,95,111,168,69,107,133,City
Santa Barbara,40,28,89,35,50,13,25,67,5,39,72,City
Santa_Monica,39,32,41,78,18,11,27,38,11,17,2,City
Seattle,215,225,178,49,106,51,78,123,78,122,96,City
Washington_DC,81,185,166,93,211,45,107,58,36,63,31,City

In [42]:
# Remove 'type' before normalising since it is a string
h = df_cities.drop("type", axis = 1)
h.columns

Index(['Shopping', 'Nightlife', 'Tours', 'Spas & Wellness',
       'Sights & Landmarks', 'Concerts & Shows', 'Museums',
       'Outdoor Activities', 'Fun & Games', 'Nature & Parks', 'Food & Drink'],
      dtype='object')

In [43]:
# Normalise the columns to range 1,10
scaler = preprocessing.MinMaxScaler(feature_range = (1,10)) 
scaled_values = scaler.fit_transform(h) 
h.loc[:,:] = scaled_values
h["type"] = df_cities["type"]

In [44]:
h

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Nature & Parks,Food & Drink
Austin,2.070485,3.166102,2.31625,1.854749,2.366594,1.751740,2.563934,2.281176,3.188356,3.790,4.847328
Boston,2.328194,2.606780,2.65375,1.427374,3.811280,1.981439,2.740984,1.635294,2.510274,3.250,4.435115
Denver,1.713656,2.779661,1.84375,1.791899,1.859002,1.730858,2.180328,1.487059,2.417808,2.350,6.496183
Disneyland_Anaheim,1.000000,1.081356,1.00000,1.000000,1.000000,1.020882,1.000000,1.000000,1.431507,1.000,1.549618
Florida_Keys,2.813877,1.711864,10.00000,1.980447,2.093275,1.104408,3.036066,10.000000,1.678082,5.095,2.580153
Hawaii,1.545154,1.050847,5.66875,1.402235,3.616052,1.793503,2.150820,6.272941,1.092466,10.000,3.198473
Houston,1.872247,3.837288,1.38250,1.804469,2.308026,2.106729,2.888525,1.529412,4.328767,3.070,3.335878
Las_Vegas,2.724670,4.549153,4.07125,3.023743,2.386117,4.696056,3.065574,3.594118,10.000000,3.610,2.717557
Los_Angeles,3.140969,4.437288,4.11625,6.555866,4.592191,3.568445,4.836066,2.598824,6.239726,5.005,4.366412
Miami,2.149780,2.240678,3.99250,2.294693,1.800434,1.375870,2.681967,3.615294,2.910959,3.295,2.717557
Monterey,1.198238,1.000000,1.34875,1.125698,1.078091,1.000000,1.413115,1.391765,1.215753,1.495,1.893130
New_Orleans,3.527533,3.491525,3.70000,1.477654,3.049892,1.939675,4.452459,1.952941,1.739726,2.035,4.709924
New_York_City,10.000000,10.000000,9.05500,10.000000,10.000000,10.000000,10.000000,3.202353,6.609589,6.310,8.900763
Orlando,2.080396,2.515254,2.14750,1.967877,1.488069,1.877030,1.619672,2.302353,3.958904,3.025,3.198473
Philadelphia,2.090308,3.562712,1.77625,1.326816,4.670282,2.148492,4.009836,1.264706,2.695205,2.710,3.954198
Portland,2.486784,3.166102,2.41750,1.666201,3.323210,1.918794,2.711475,1.995294,2.849315,6.805,7.870229
San_Diego,2.288546,3.196610,4.63375,2.420391,2.913232,2.064965,3.154098,4.335294,3.558219,4.825,8.625954
San_Francisco,4.171806,4.406780,4.69000,2.131285,8.731020,2.837587,4.157377,2.694118,2.972603,5.680,10.000000
Santa Barbara,1.297357,1.244068,1.87750,1.364525,1.722343,1.125290,1.619672,1.624706,1.000000,2.620,5.809160
Santa_Monica,1.287445,1.284746,1.33750,1.905028,1.097614,1.083527,1.678689,1.317647,1.184932,1.630,1.000000
Seattle,3.031938,3.247458,2.87875,1.540503,2.815618,1.918794,3.183607,2.217647,3.250000,6.355,7.458015
Washington_DC,1.703744,2.840678,2.74375,2.093575,4.865510,1.793503,4.039344,1.529412,1.955479,3.700,2.992366

In [49]:
# Remove irrelevant columns from df_nature
df_nature_relevant = df_nature[["Tours", "Sights & Landmarks", "Outdoor Activities",
                               "Fun & Games", "Nature & Parks"]]
# Remove 'type' before normalising since it is a string
#g = df_nature_relevant.drop("type", axis = 1)
df_nature_relevant.columns

Index(['Tours', 'Sights & Landmarks', 'Outdoor Activities', 'Fun & Games',
       'Nature & Parks'],
      dtype='object')

In [50]:
# Normalise the columns to range 1,10
scaler = preprocessing.MinMaxScaler(feature_range = (1,10)) 
scaled_values = scaler.fit_transform(df_nature_relevant) 
df_nature_relevant.loc[:,:] = scaled_values
#h["type"] = df_cities["type"]

C:\Users\Shrivatav\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
C:\Users\Shrivatav\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

In [51]:
df_nature_relevant

,Tours,Sights & Landmarks,Outdoor Activities,Fun & Games,Nature & Parks
Arches_National_Park,1.000000,2.384615,1.000000,1.000000,2.644231
Bryce_Canyon_National_Park,1.098901,3.076923,1.252809,1.000000,2.471154
Death_Valley_National_Park,1.098901,6.076923,1.101124,1.000000,3.682692
Denali_National_Park,4.461538,1.692308,2.264045,1.428571,1.865385
Glacier_National_Park,1.296703,1.461538,1.404494,1.000000,4.548077
Grand_Canyon_National_Park,2.879121,10.000000,2.870787,1.000000,4.201923
Grand_Teton_National_Park,2.681319,4.000000,1.859551,1.000000,3.163462
Joshua_Tree_National_Park,1.296703,3.307692,1.151685,1.000000,2.730769
Lake_Tahoe,9.901099,6.538462,10.000000,10.000000,7.836538
Monument_Valley,3.175824,1.000000,1.151685,1.000000,1.000000
Niagara_Falls,3.571429,3.538462,1.202247,4.857143,2.211538
Sedona,10.000000,6.769231,6.106742,6.142857,6.019231
Sequoia_National_Park,1.098901,5.846154,1.910112,1.000000,3.942308
Yellowstone_National_Park,2.483516,7.000000,2.820225,1.000000,10.000000
Yosemite_National_Park,2.285714,7.230769,2.820225,1.000000,7.836538
Zion_National_Park,1.197802,2.846154,2.011236,1.000000,3.855769

In [52]:
# Export both dataframes to csv files
h.to_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data_cities.csv")
df_nature_relevant.to_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data_nature.csv")

In [16]:
'''
from sklearn import preprocessing

cols_to_normalise = ["Shopping", "Nightlife", "Tours", "Spas & Wellness", "Sights & Landmarks", "Concerts & Shows", "Museums", 
                "Outdoor Activities", "Fun & Games", "Nature & Parks", "Food & Drink"]

minmax_scale = preprocessing.MinMaxScaler(feature_range = (1,10)).fit(df_new[cols_to_normalise])
df_minmax = minmax_scale.transform(df_new[cols_to_normalise])

df_minmax

df_normalised = pd.DataFrame(df_minmax, columns=cols_to_normalise)
df_normalised["type"] = df_new["type"]
df_normalised

df_new["type"]

inp_data = pd.read_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data.csv")

inp_data.head()

minmax_scale = preprocessing.MinMaxScaler(feature_range = (0,10)).fit(inp_data[['Nature & Parks']])
df_minmax = minmax_scale.transform(inp_data[['Nature & Parks']])

df_minmax
'''

In [ ]:
'''
xx = {
    "New_York_City" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60763-Activities-New_York_City_New_York.html"
    },
    "San_Francisco" : {
        "type" : "City",
        "url": "https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html"
    },
    "Los_Angeles" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g32655-Activities-Los_Angeles_California.html"
    }
}
'''

In [ ]:
#places_and_tags_dict_test = {}

In [ ]:
'''
for k,v in xx.items():
    print(k)
    #print(v["url"])
    dict_tags = get_tags_from_url(v["url"])
    #places_and_tags_dict_test[k] = dict_tags
    #places_and_tags_dict_test[k]["type"] = v["type"]
    #places_and_tags_dict_test[k]["url"] = dict_tags
    places_and_tags_dict_test[k] = {}
    places_and_tags_dict_test[k]["type"] = v["type"]
    places_and_tags_dict_test[k]["url"] = dict_tags
''' 
#d.quit()

In [ ]:
#d.quit()

In [ ]:
#places_and_tags_dict_test