In [1]:
import requests
import time
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support import ui
import pandas as pd

In [2]:
# Define header to prevent errors
user_agent = "Mozilla/44.0.2 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/9.0.2"
headers = {'User-Agent': user_agent}

In [3]:
# Set webdriver - global
d = webdriver.Chrome("C:\\Users\\Shrivatav\\Downloads\\chromedriver_win32\\chromedriver.exe")

In [4]:
wait = ui.WebDriverWait(d, 10)

In [5]:
url_dict = {
    "New_York_City" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60763-Activities-New_York_City_New_York.html"
    },
    "San_Francisco" : {
        "type" : "City",
        "url": "https://www.tripadvisor.com/Attractions-g60713-Activities-San_Francisco_California.html"
    },
    "Los_Angeles" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g32655-Activities-Los_Angeles_California.html"
    },
    "Las_Vegas" : {
        "type" : "City",
         "url" : "https://www.tripadvisor.com/Attractions-g45963-Activities-Las_Vegas_Nevada.html"   
    },
    "Grand_Canyon_National_Park" : {
        "type" : "Natural",
        "url": "https://www.tripadvisor.com/Attractions-g143028-Activities-Grand_Canyon_National_Park_Arizona.html"
    },
    "Yellowstone_National_Park" : {
        "type" : "Natural",
        "url": "https://www.tripadvisor.com/Attractions-g60999-Activities-Yellowstone_National_Park_Wyoming.html"
    },
    "Disneyland_Anaheim" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g29092-Activities-Anaheim_California.html"
    },
    "Washington_DC" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g28970-Activities-Washington_DC_District_of_Columbia.html"
    },
    "Yosemite_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g61000-Activities-Yosemite_National_Park_California.html"
    },
    "Miami" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34438-Activities-Miami_Florida.html"
    },
    "Orlando" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34515-Activities-Orlando_Florida.html"
    },
    "Zion_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143057-Activities-Zion_National_Park_Utah.html"
    },
    "Santa_Monica" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33052-Activities-Santa_Monica_California.html"
    },
    "Seattle" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60878-Activities-Seattle_Washington.html"
    },
    "Boston" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60745-Activities-Boston_Massachusetts.html"
    },
    "San_Diego" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60750-Activities-San_Diego_California.html"
    },
    "Florida_Keys" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g34340-Activities-Florida_Keys_Florida.html"
    },
    "Hawaii" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g28932-Activities-Hawaii.html"
    },
    "Bryce_Canyon_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143015-Activities-Bryce_Canyon_National_Park_Utah.html"
    },
    "Glacier_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143026-Activities-Glacier_National_Park_Montana.html"
    },
    "Grand_Teton_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143029-Activities-Grand_Teton_National_Park_Wyoming.html"
    },
    "New_Orleans" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60864-Activities-New_Orleans_Louisiana.html"
    },
    "Arches_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143011-Activities-Arches_National_Park_Utah.html"
    },
    "Monterey" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g32737-Activities-Monterey_Monterey_County_California.html"
    },
    "Niagara_Falls" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g48261-Activities-Niagara_Falls_New_York.html"
    },
    "Sequoia_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143050-Activities-Sequoia_and_Kings_Canyon_National_Park_California.html"
    },
    "Sedona" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g31352-Activities-Sedona_Arizona.html"
    },
    "Lake_Tahoe" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g155987-Activities-Lake_Tahoe_California_California.html"
    },
    "Philadelphia" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g60795-Activities-Philadelphia_Pennsylvania.html"
    },
    "Joshua_Tree_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143037-Activities-Joshua_Tree_National_Park_California.html"
    },
    "Santa Barbara" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33045-Activities-Santa_Barbara_California.html"
    },
    #"Redwood_National_and_State_Parks" : "https://www.tripadvisor.com/Attractions-g2193168-Activities-Redwood_National_Park_California.html",
    "Denver" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g33388-Activities-Denver_Colorado.html"
    },
    "Austin" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g30196-Activities-Austin_Texas.html"
    },
    "Denali_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143022-Activities-Denali_National_Park_and_Preserve_Alaska.html"
    },
    "Houston" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g56003-Activities-Houston_Texas.html"
    },
    "Portland" : {
        "type" : "City",
        "url" : "https://www.tripadvisor.com/Attractions-g52024-Activities-Portland_Oregon.html"
    },
    "Death_Valley_National_Park" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g143021-Activities-Death_Valley_National_Park_California.html"
    },
    "Monument_Valley" : {
        "type" : "Natural",
        "url" : "https://www.tripadvisor.com/Attractions-g57072-Activities-Monument_Valley_Utah.html"
    }
}

In [7]:
def get_tags_from_url_city(input_url):
    # Get response from url
    response = requests.get(input_url, headers = headers)
    # Encode response for parsing
    html = response.text.encode('utf-8')
    # Soupify the response
    soup = BeautifulSoup(html, "lxml")
    # Get tags - they are contained in class "taLnk" as hyperlinked elements
    tag_elements = soup.findAll("a", {"class":"taLnk"})
    
    dict_of_tags = {}
    
    if (len(tag_elements) != 0):
        # Iterate over tag_elements and exctract those which have parentheses 
        # as they are the relevant items
        print("1st type")
        tags_list = []
        for i in tag_elements:
            strng = i.string
            if("(" in strng):
                tags_list.append(strng)
    
        # Create final list of tags
        for item in tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value
    else:
        # Second kind of web page with list of 'Things to Do' at the bottom of the page
        # Use selenium to automate browser functionality
        # Browser opens the input_url, scrolls till the bottom of the page,
        # clicks on 'Show All' button, the entire list becomes visible; then scrapes it
        print("2nd type")
        # Sleep for some time to prevent too many requests
        time.sleep(5)
        d.get(input_url)
        show_more = wait.until(lambda d: d.find_element_by_css_selector("[class='ui_container'] div:nth-of-type(1) .caret-down"))
        d.execute_script("arguments[0].click();",show_more)
        soup = BeautifulSoup(d.page_source,"lxml")
        items = [item.text for item in soup.select("[class='ui_container'] div:nth-of-type(1) a[href^='/Attractions-']")]
        
        # Create final list of tags
        for item in items:#tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value
        
    return dict_of_tags

In [8]:
def get_tags_from_url_nature(input_url):
    # Get response from url
    response = requests.get(input_url, headers = headers)
    # Encode response for parsing
    html = response.text.encode('utf-8')
    # Soupify the response
    soup = BeautifulSoup(html, "lxml")
    # Get tags - they are contained in class "taLnk" as hyperlinked elements
    tag_elements = soup.findAll("a", {"class":"taLnk"})
    
    dict_of_tags = {}
    
    if (len(tag_elements) != 0):
        # Iterate over tag_elements and exctract those which have parentheses 
        # as they are the relevant items
        print("1st type")
        tags_list = []
        for i in tag_elements:
            strng = i.string
            if("(" in strng):
                tags_list.append(strng)
    
        # Create final list of tags
        for item in tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value
        
        # Finding numbers for 'Good for adrenaline seekers'
        split_url = input_url.split('Activities')
        new_url = 'Activities-zft11312'.join(split_url)
        # Get response from url
        response = requests.get(new_url, headers = headers)
        # Encode response for parsing
        html = response.text.encode('utf-8')
        # Soupify the response
        soup = BeautifulSoup(html, "lxml")
        adrenaline_divs = soup.findAll("div", {"class": "attraction_element"})
        dict_of_tags["Adrenaline"] = len(adrenaline_divs)
        
        
    else:
        # Second kind of web page with list of 'Things to Do' at the bottom of the page
        # Use selenium to automate browser functionality
        # Browser opens the input_url, scrolls till the bottom of the page,
        # clicks on 'Show All' button, the entire list becomes visible; then scrapes it
        print("2nd type")
        # Sleep for some time to prevent too many requests
        time.sleep(5)
        d.get(input_url)
        show_more = wait.until(lambda d: d.find_element_by_css_selector("[class='ui_container'] div:nth-of-type(1) .caret-down"))
        d.execute_script("arguments[0].click();",show_more)
        soup = BeautifulSoup(d.page_source,"lxml")
        items = [item.text for item in soup.select("[class='ui_container'] div:nth-of-type(1) a[href^='/Attractions-']")]
        
        # Create final list of tags
        for item in items:#tags_list:
            items_list = item.split('(')
            name = items_list[0].rstrip()
            # Get value
            value = item[item.find("(") + 1:item.find(")")]
            dict_of_tags[name] = value

        # Works
        a = soup.find(lambda tag:tag.name == "a" and "Good for Adrenaline Seekers" in tag.text)
        a_text = a.text
        value = a_text[a_text.find("(") + 1:a_text.find(")")]
        dict_of_tags["Adrenaline"] = value
        
    return dict_of_tags

In [9]:
'''
def newfun(input_url):
    if type == "City":
        get_tags_from_url(input_url)
    else:
        # If type is 'Nature' we will scrape 'Good for Adrenaline Seekers' also
        get_data_nature(input_url)
'''

places_and_tags_city_dict = {}
places_and_tags_nature_dict = {}

for k,v in url_dict.items():
    print(k)
    if v["type"] == "City":
        dict_tags = get_tags_from_url_city(v["url"])
        places_and_tags_city_dict[k] = dict_tags
    else:
        dict_tags = get_tags_from_url_nature(v["url"])
        places_and_tags_nature_dict[k] = dict_tags

# Close web driver
d.quit

New_York_City
2nd type
San_Francisco
2nd type
Los_Angeles
2nd type
Las_Vegas
2nd type
Grand_Canyon_National_Park
2nd type
Yellowstone_National_Park
2nd type
Disneyland_Anaheim
2nd type
Washington_DC
2nd type
Yosemite_National_Park
2nd type
Miami
2nd type
Orlando
2nd type
Zion_National_Park
1st type
Santa_Monica
2nd type
Seattle
2nd type
Boston
2nd type
San_Diego
2nd type
Florida_Keys
2nd type
Hawaii
1st type
Bryce_Canyon_National_Park
1st type
Glacier_National_Park
1st type
Grand_Teton_National_Park
2nd type
New_Orleans
2nd type
Arches_National_Park
1st type
Monterey
1st type
Niagara_Falls
2nd type
Sequoia_National_Park
1st type
Sedona
2nd type
Lake_Tahoe
2nd type
Philadelphia
2nd type
Joshua_Tree_National_Park
1st type
Santa Barbara
2nd type
Denver
2nd type
Austin
2nd type
Denali_National_Park
2nd type
Houston
2nd type
Portland
2nd type
Death_Valley_National_Park
1st type
Monument_Valley
2nd type

In [18]:
# Convert this dictionary to a pandas DataFrame
df_city = pd.DataFrame.from_dict(places_and_tags_city_dict, orient = 'index')
# Replace NaN values with 0
df_city.fillna(0, inplace = True)
df_city.head()

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Transportation,Nature & Parks,Food & Drink,Classes & Workshops,Boat Tours & Water Sports,Traveler Resources,Day Trips,Events,Water & Amusement Parks,Zoos & Aquariums,Casinos & Gambling
Austin,118,217,129,74,83,43,57,129,76,17,65,60,27,54,9,0,3,2,3,1
Boston,146,162,158,40,158,54,63,69,54,63,53,53,14,44,19,13,0,0,2,1
Denver,82,179,86,70,57,42,44,54,52,36,33,83,18,9,3,4,0,2,2,0
Disneyland_Anaheim,10,12,11,6,13,8,4,8,19,13,3,10,3,1,2,9,0,8,0,0
Florida_Keys,193,74,811,84,69,12,73,858,27,19,94,25,17,741,10,0,1,0,7,1

The columns are of the type 'object'. Convert them to numeric.

In [45]:
# Convert all columns of df_city to numeric
df_city= df_city.apply(pd.to_numeric)
df_city.head()

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Transportation,...,Food & Drink,Classes & Workshops,Boat Tours & Water Sports,Traveler Resources,Day Trips,Events,Water & Amusement Parks,Zoos & Aquariums,Casinos & Gambling,Fun/Games/Activities
Austin,118,217,129,74,83,43,57,129,76,17,...,60,27,54,9,0,3,2,3,1,59108.5
Boston,146,162,158,40,158,54,63,69,54,63,...,53,14,44,19,13,0,0,2,1,73081.0
Denver,82,179,86,70,57,42,44,54,52,36,...,83,18,9,3,4,0,2,2,0,41089.5
Disneyland_Anaheim,10,12,11,6,13,8,4,8,19,13,...,10,3,1,2,9,0,8,0,0,506.0
Florida_Keys,193,74,811,84,69,12,73,858,27,19,...,25,17,741,10,0,1,0,7,1,9687.0

Combine "Outdoor Activities" and "Fun & Games" into one column by taking their mean. Call it "Fun/Games/Activities

In [46]:
df_city['Fun/Games/Activities'] = df_city_new[['Shopping', 'Nightlife']].mean(axis=1)

In [47]:
df_city.head()

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Outdoor Activities,Fun & Games,Transportation,...,Food & Drink,Classes & Workshops,Boat Tours & Water Sports,Traveler Resources,Day Trips,Events,Water & Amusement Parks,Zoos & Aquariums,Casinos & Gambling,Fun/Games/Activities
Austin,118,217,129,74,83,43,57,129,76,17,...,60,27,54,9,0,3,2,3,1,167.5
Boston,146,162,158,40,158,54,63,69,54,63,...,53,14,44,19,13,0,0,2,1,154.0
Denver,82,179,86,70,57,42,44,54,52,36,...,83,18,9,3,4,0,2,2,0,130.5
Disneyland_Anaheim,10,12,11,6,13,8,4,8,19,13,...,10,3,1,2,9,0,8,0,0,11.0
Florida_Keys,193,74,811,84,69,12,73,858,27,19,...,25,17,741,10,0,1,0,7,1,133.5

Remove irrelevant columns.

In [49]:
cols_to_keep = ["Shopping", "Nightlife", "Tours", "Spas & Wellness", "Sights & Landmarks", "Concerts & Shows", "Museums", 
                "Fun/Games/Activities", "Nature & Parks", "Food & Drink"]
df_city_new = df_city[cols_to_keep]
df_city_new.columns

Index(['Shopping', 'Nightlife', 'Tours', 'Spas & Wellness',
       'Sights & Landmarks', 'Concerts & Shows', 'Museums',
       'Fun/Games/Activities', 'Nature & Parks', 'Food & Drink'],
      dtype='object')

In [50]:
# Normalise the columns to range 1,10
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler(feature_range = (1,10)) 
scaled_values = scaler.fit_transform(df_city_new) 
df_city_new.loc[:,:] = scaled_values

C:\Users\Shrivatav\Anaconda3\lib\site-packages\pandas\core\indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [51]:
df_city_new

,Shopping,Nightlife,Tours,Spas & Wellness,Sights & Landmarks,Concerts & Shows,Museums,Fun/Games/Activities,Nature & Parks,Food & Drink
Austin,2.069307,3.166102,2.32750,1.854749,2.366594,1.751740,2.563934,2.577268,3.790,4.984733
Boston,2.346535,2.606780,2.65375,1.427374,3.830803,1.981439,2.740984,2.441209,3.250,4.503817
Denver,1.712871,2.779661,1.84375,1.804469,1.859002,1.730858,2.180328,2.204367,2.350,6.564885
Disneyland_Anaheim,1.000000,1.081356,1.00000,1.000000,1.000000,1.020882,1.000000,1.000000,1.000,1.549618
Florida_Keys,2.811881,1.711864,10.00000,1.980447,2.093275,1.104408,3.036066,2.234602,5.095,2.580153
Hawaii,1.544554,1.050847,5.66875,1.402235,3.616052,1.793503,2.150820,1.262038,10.000,3.198473
Houston,1.871287,3.837288,1.39375,1.804469,2.308026,2.106729,2.888525,2.809071,3.070,3.404580
Las_Vegas,2.722772,4.549153,4.08250,3.036313,2.386117,4.696056,3.065574,3.595185,3.610,2.786260
Los_Angeles,3.168317,4.447458,4.11625,6.555866,4.728850,3.589327,4.836066,3.771557,5.050,4.366412
Miami,2.158416,2.250847,4.00375,2.294693,1.800434,1.375870,2.681967,2.169093,3.295,2.717557
Monterey,1.198020,1.000000,1.34875,1.125698,1.078091,1.000000,1.413115,1.060470,1.495,1.824427
New_Orleans,3.524752,3.501695,3.70000,1.477654,3.049892,1.939675,4.452459,3.484323,2.035,4.709924
New_York_City,10.000000,10.000000,9.07750,10.000000,10.000000,10.000000,10.000000,10.000000,6.310,8.832061
Orlando,2.079208,2.515254,2.14750,1.967877,1.488069,1.877030,1.619672,2.259798,3.025,3.198473
Philadelphia,2.089109,3.562712,1.77625,1.339385,4.670282,2.148492,4.009836,2.783875,2.710,3.954198
Portland,2.495050,3.166102,2.44000,1.666201,3.323210,1.918794,2.711475,2.793953,6.805,8.007634
San_Diego,2.287129,3.196610,4.66750,2.420391,2.913232,2.064965,3.154098,2.703247,4.825,8.694656
San_Francisco,4.207921,4.406780,4.71250,2.156425,8.750542,2.837587,4.216393,4.280515,5.680,10.000000
Santa Barbara,1.297030,1.244068,1.87750,1.364525,1.722343,1.125290,1.619672,1.231803,2.620,5.809160
Santa_Monica,1.287129,1.284746,1.33750,1.905028,1.097614,1.083527,1.678689,1.246920,1.630,1.000000
Seattle,3.029703,3.247458,2.86750,1.540503,2.815618,1.918794,3.183607,3.106383,6.355,7.526718
Washington_DC,1.702970,2.840678,2.74375,2.118715,4.904555,1.793503,4.039344,2.229563,3.745,2.992366

In [52]:
df_nature = pd.DataFrame.from_dict(places_and_tags_nature_dict, orient = 'index')
df_nature.fillna(0, inplace = True)
df_nature

,Outdoor Activities,Nature & Parks,Sights & Landmarks,Tours,Day Trips,Museums,Shopping,Boat Tours & Water Sports,Traveler Resources,Concerts & Shows,Classes & Workshops,Adrenaline,Spas & Wellness,Transportation,Nightlife,Fun & Games,Food & Drink,Casinos & Gambling,Zoos & Aquariums,Water & Amusement Parks
Arches_National_Park,13,22,7,0,0,0,0,0,1,0,0,11,0,0,0,0,0,0,0,0
Bryce_Canyon_National_Park,18,20,10,1,0,0,1,0,1,0,0,11,0,1,0,0,0,0,0,0
Death_Valley_National_Park,15,34,23,1,0,1,0,0,1,0,0,6,0,0,0,0,0,0,0,0
Denali_National_Park,38,13,4,35,0,3,5,8,3,4,0,22,0,2,0,1,0,1,0,0
Glacier_National_Park,21,44,3,3,0,0,0,2,1,0,1,14,0,0,0,0,0,0,0,0
Grand_Canyon_National_Park,50,40,40,19,9,4,4,2,1,1,1,35,0,0,0,0,0,0,0,0
Grand_Teton_National_Park,30,28,14,17,2,1,0,9,2,1,0,6,0,0,0,0,0,0,0,0
Joshua_Tree_National_Park,16,23,11,3,0,0,0,0,1,0,2,8,0,0,0,0,0,0,0,0
Lake_Tahoe,192,83,25,90,0,21,44,56,5,3,6,36,34,4,16,21,7,0,0,0
Monument_Valley,16,3,1,22,0,1,4,0,0,0,0,2,0,0,0,0,0,0,0,0
Niagara_Falls,17,17,12,26,1,9,11,6,1,4,0,11,2,11,16,9,2,1,1,1
Sedona,115,61,26,92,8,35,137,5,5,3,17,42,87,2,7,12,13,0,0,0
Sequoia_National_Park,31,37,22,1,0,0,0,0,2,0,0,7,0,0,0,0,0,0,0,0
Yellowstone_National_Park,49,107,27,15,2,0,2,3,8,1,0,11,1,1,0,0,0,0,0,0
Yosemite_National_Park,49,82,28,13,4,3,2,5,5,2,2,25,0,3,0,0,0,0,0,0
Zion_National_Park,33,36,9,2,0,0,0,0,1,0,0,16,0,0,0,0,0,0,0,0

In [59]:
# Keep only relevant columns
cols_to_keep = ["Outdoor Activities", "Nature & Parks", "Sights & Landmarks", "Tours", "Adrenaline"]

In [60]:
df_nature_new = df_nature[cols_to_keep]
df_nature_new.columns

Index(['Outdoor Activities', 'Nature & Parks', 'Sights & Landmarks', 'Tours',
       'Adrenaline'],
      dtype='object')

In [61]:
# Convert all columns of df_city to numeric
df_nature_new = df_nature_new.apply(pd.to_numeric)

In [62]:
# Normalise the columns to range 1,10
scaled_values = scaler.fit_transform(df_nature_new) 
df_nature_new.loc[:,:] = scaled_values

In [63]:
df_nature_new

,Outdoor Activities,Nature & Parks,Sights & Landmarks,Tours,Adrenaline
Arches_National_Park,1.000000,2.644231,2.384615,1.000000,3.025
Bryce_Canyon_National_Park,1.251397,2.471154,3.076923,1.097826,3.025
Death_Valley_National_Park,1.100559,3.682692,6.076923,1.097826,1.900
Denali_National_Park,2.256983,1.865385,1.692308,4.423913,5.500
Glacier_National_Park,1.402235,4.548077,1.461538,1.293478,3.700
Grand_Canyon_National_Park,2.860335,4.201923,10.000000,2.858696,8.425
Grand_Teton_National_Park,1.854749,3.163462,4.000000,2.663043,1.900
Joshua_Tree_National_Park,1.150838,2.730769,3.307692,1.293478,2.350
Lake_Tahoe,10.000000,7.923077,6.538462,9.804348,8.650
Monument_Valley,1.150838,1.000000,1.000000,3.152174,1.000
Niagara_Falls,1.201117,2.211538,3.538462,3.543478,3.025
Sedona,6.128492,6.019231,6.769231,10.000000,10.000
Sequoia_National_Park,1.905028,3.942308,5.846154,1.097826,2.125
Yellowstone_National_Park,2.810056,10.000000,7.000000,2.467391,3.025
Yosemite_National_Park,2.810056,7.836538,7.230769,2.271739,6.175
Zion_National_Park,2.005587,3.855769,2.846154,1.195652,4.150

In [64]:
# Export both dataframes to csv files - to be used in R for building a web application
# Export both dataframes to csv files
df_city_new.to_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data_cities_1201.csv")
df_nature_new.to_csv(r"C:\Users\Shrivatav\Desktop\UMN\Homework\Fall 2018\AI 1\Project\data_nature_1201.csv")